### ISSUE TITLE
Use sqlite in memory?

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3/testing-framework#202]
As far as I understand it is currently impossible to use sqlite in memory.

https://github.com/TYPO3/testing-framework/blob/6.4.2/Classes/Core/Functional/FunctionalTestCase.php#L308 and the following line will prevent this.

What is the reason to always use a local file?
Wouldn't it make sense to make this configurable and allow an in memory database?
As far as I understand it would be enough to use an empty string as file path.

**Comment by bmack** [comment]
no reasoning, this is how we tested it when we implemented it 2 years ago. If you're up for it, feel free to create a PR.

**Comment by lolli42** [comment]
When it comes to test performance, it's probably easier to mount the file into a ramdisk.
core CI does that already since the entire /var/lib/docker is a ramdisk.
Moving the .sqlite file to some sub-directory could help to simplify this for local test execution, since a directory name is easier to map in docker-compose files than the single .sqlite file that contains a hash. A patch in this direction is appreciated.

If you refer to the sqlite built-in 'file::memory' specification, I'm not sure if that would help us much:
https://www.sqlite.org/inmemorydb.html "The database ceases to exist as soon as the database connection is closed."
This is counter productive for functional test cases with mulitple tests, since the schema analyzer would have to create a full set for each test, the current implementation does that only once per test case for the first test (slow), subsequent tests then truncate (quick). I'd guess that approach is quicker in the end than a full new DB per test - memory driven or not.

I'll close the issue for now since I see no huge benefit in doing so.
Please ping me if you disagree and want to work on it, I'd reopen in this case.
