### ISSUE TITLE
Acceptance tests: Fix page tree navigation - Wait for children loaded

### ISSUE THREAD

**Issue by alexander-nitsche** [TYPO3/testing-framework#245]
### Problem

The typo3/testing-framework acceptance test action \TYPO3\TestingFramework\Core\Acceptance\Helper\AbstractPageTree::openTreePath tries to open the child element without waiting for all children being loaded via AJAX.

### Steps to reproduce

1) Create a page tree with at least two levels, e.g.
   ```
   | - Congratulations
      | - Pages
         | - 2 Columns
   ```
2) Write an acceptance test which opens the page tree along the path to that page, for example 
   ```
   $pageTree->openPath(["Congratulations", "Pages", "2 Columns"]);
   ```
3) Run the acceptance test

### Expected

The acceptance test opens the page tree and navigates to the page "2 Columns".

### Actual

The acceptance test fails with
```
Failed asserting that any element by 'g.nodes > .node' on page /typo3temp/var/tests/acceptance/typo3/module/web/list[total 12 elements]
contains text '2 Columns'
```
as the children seem to be not fully loaded by AJAX or post-processed yet.

### Problem

The implementation assumes in line https://github.com/TYPO3/testing-framework/blob/master/Classes/Core/Acceptance/Helper/AbstractPageTree.php#L91
```
$context->findElement(\Facebook\WebDriver\WebDriverBy::cssSelector('.chevron.collapsed'))->click();
```
that the click synchronously opens the children menu, but it seems to load it asynchronously. 

The problem can be fixed for example by inserting a waiting period of 0.1 seconds:
```
$context->findElement(\Facebook\WebDriver\WebDriverBy::cssSelector('.chevron.collapsed'))->click();
$webDriver->wait(0.1);
```
but maybe there is a smarter solution to that problem?

**Comment by sbuerk** [comment]
I think, we can say that this is eventually related to the current existing flaky pagetree test in core (main).

Originally there has been a check if there are running ajax requests, using the jquery ajax counter - which has been removed.

If I understand this correctly, maybe we should find a proper solution/replacement to check/wait until all running ajax requests has been finished, with eventually a "safe-off wait" afterwards . before expeting any childs etc. So that this can be used generally for waiting for ajax responses etc.

I talked with Jochen Roth (not knowing his github name to mention him), as he had tried to stabilize the pagetreecest tests without this ajax (which has ben stripped down to a simply wait timeout when jquery ajax counter has been replaced).

Not sure what he came up, and myself bound to quite other tasks - but I'm willing to share my thoughts/idea's, maybe in a short slack call if some want's to pick that up and make it more a generall ajax wait utility, either in core or better in TF.

**Comment by alexander-nitsche** [comment]
I would opt for specific ajax events thrown in this situation, as we do in similar situations in PHP code. For example with throwing "startLoadingPageTree" and "endLoadingPageTree" we can already fix the flaky page tree acceptance tests. At the same time i would opt against a general ajax counter as it is not precise and might induce unnecessary waiting time.

**Comment by lolli42** [comment]
Hey.

This issue is quite old, the page tree navigation works for core and extensions and the described problem has been solved differently in the consuming package already.

I hope its ok to close here for now.
