### ISSUE TITLE
Login ($I->useExistingSession('admin')) doesn’t work after “Protect persisted session IDs from being used directly”

### ISSUE THREAD

**Issue by dawind** [TYPO3/testing-framework#247]
With https://git.typo3.org/Packages/TYPO3.CMS.git/commit/0b96d4bda222f2ce39e858e1a4eb874a71e2b3d0 the be_sessions.xml must use other session ids.

This change in the session ids has been reflected in the core acceptance tests as a new be_sessions fixture is introduced within the commit as part of the core extension.

Test executions depending on the fixture via 
`'PACKAGE:typo3/testing-framework/Resources/Core/Acceptance/Fixtures/be_sessions.xml'`
 of the testing framework for the backend login will fail, as the ses_id are not valid anymore.

**Comment by lolli42** [comment]
Yeah. That's nasty. We had similar issues in other files when for instance db fields changed.
I for instance adapted ext:styleguide twice due to this.
These files are especially hard to maintain when TF supports multiple core versions at once: If then core adds or drops db fields in one version only, TF can't support both schema at the same time.
My gut feeling is that these .xml files in the testing-framework don't help us much - I tend to mark them deprecated saying that extensions should maybe them on their own, but I'll have to give this some more thoughts.
What do you think?

**Comment by dawind** [comment]
In general, I think it would be the best option to deprecate superfluous fixtures.

In case of be_users, be_groups and be_sessions, I would not prefer this option as the testing framework itself relies on this kind of fixtures. The LoginHelper needs them to work (https://github.com/TYPO3/testing-framework/blob/master/Classes/Core/Acceptance/Helper/Login.php).

The main problem is the premise you mentioned:

Supporting different TYPO3 versions at once will be hard to impossible. The best solution might be a change in the premise by doing the versioning of the testing framework according to the TYPO3 Core extensions. Provided that versioning, composer can take over and could solve the issue.

I don't know what effect this change might have to extensions supporting different Core versions in one branch, as I prefer one branch per core version.

**Comment by lolli42** [comment]
The Login helper has no direct dependencies to the fixture files, it can be used to login anyone.

I'll continue on this issue now: We'll introduce a csv import feature, will then deprecate the xml import together with the fixtures.
