### ISSUE TITLE
Build-Folder with runTests.sh is missing after composer installation

### ISSUE THREAD

**Issue by bonokburn** [TYPO3/testing-framework#401]
Hello all,

**Problem**
maybe I have a thinking error or do something wrong, but where do I find the command runScripts.sh in a Composer based TYPO3 installation? The command is not present in the package typo3/cms-core and if I add the following dependency:

**Reproduce**
composer require --dev typo3/testing-framework:7.x-dev

the "Build" folder is missing completely with the Scripts subfolder and runTests.sh. The "Tests" folder that I see in Github is also missing. Only Classes and Resources are present in the vendor folder. I don't understand why these folders are not created by Composer.

Thanks a lot!
Greetings
Frank

**Comment by sbuerk** [comment]
The build folder is meant for testing the framework itself. Tests are normally not shipped with composer (zip) archives, which is a "normal" thing.

The TF Build folder is excluded through the gitattributes file, which composer/packagist/etc respects when building "archives" of the repo: [See .gitattributes](https://github.com/TYPO3/testing-framework/blob/ec6ce3a2731aa2dda89c42a4c9af9d1712457795/.gitattributes#L6)

In the "mono repo" of the core it is slightly different. The build folder resists in the monorepo. Each "typo3/sysext/" is splittet in single repositories and uploaded to git, and each of these single repositories are used to greate zip archives (packagist and co). Here, Build folders and mono repo related stuff are simply not available.

If you require core system extension as source, they should be have at least the tests included. If you require TF from source instead of dist it "should be" the same.

Regarding the runTests.sh there are a lot of things which is project related, so it do not make much sense to ship a generic one. Beside this, it is not really mandantory. Even if personally I can recommend it.

You have to copy it from the source (either [this repo](https://github.com/typo3/testing-framework), [typo3/typo3 MonoRepo]https://github.com/typo3/typo3 , [typo3/cms-styleguide](https://github.com/typo3/styleguide), and the one or other extension using it to for testing. And adopt it to your needs:

- your scripts you want/need (linter, analyser, etc)
- which php you want to support
- which db versions you want to test
- and so on ...

I can recommend to have a peak into typo3/cms-styleguide (single core version testing) ... or if you want a v11/v12 testing you may have a look into [lolli42/dbdoctor](https://github.com/lolli42/dbdoctor) - which may be adopted for v10/v11 testing to if really needed.

If you want, you can use "--prefer-source" if you require one package etc .. or you can add a configuration to your composer.json to define which you want as source and which you want to be using dist/auto, read-up: https://getcomposer.org/doc/06-config.md#preferred-install

```json
{
    "config": {
        "preferred-install": {
            "typo3/cms-core": "source",
            "typo3/testing-framework": "source",
            "internal-projects/*": "auto",
            "*": "dist"
        }
    }
}
```

or something like that. In the end, would not recommend it. Better copy one time the runTests.sh and stuff you need to your repo. and adjust it to your needs.

**Comment by bonokburn** [comment]
Thanks for the great explanation! It answers all my questions! Have a nice weekend!
Frank
