### ISSUE TITLE
Not compatible with typo3/cms-composer-installers v4.0.0-RC1

### ISSUE THREAD

**Issue by oliverklee** [TYPO3/testing-framework#403]
### What are you trying to achieve?

On a new TYPO3-11LTS-based site with typo3/testing-framework 6.1.6 and typo3/cms-composer-installers 4.0.0-rc1, I created some (dummy) unit tests for my site package and ran them using a copy of the TF-provided `UnitTests.xml`.

Running `vendor/bin/phpunit -c config/UnitTests.xml` (from within my DDEV-based container), I expect to get something like this:

```
$ vendor/bin/phpunit -c config/UnitTests.xml
PHPUnit 9.5.24 #StandWithUkraine

...............................................................  63 / 744 (  8%)
............................................................... 126 / 744 ( 16%)
............................................................... 189 / 744 ( 25%)
............................................................... 252 / 744 ( 33%)
............................................................... 315 / 744 ( 42%)
............................................................... 378 / 744 ( 50%)
............................................................... 441 / 744 ( 59%)
............................................................... 504 / 744 ( 67%)
............................................................... 567 / 744 ( 76%)
............................................................... 630 / 744 ( 84%)
............................................................... 693 / 744 ( 93%)
...................................................             744 / 744 (100%)

Time: 00:00.537, Memory: 20.00 MB

OK (744 tests, 891 assertions)
```

(with fewer tests, of course, as I currently only have 1 dummy test to check that the setup works)

### What do you get instead?

```
$ vendor/bin/phpunit -c config/UnitTests.xml
PHPUnit 9.5.24 #StandWithUkraine

Error in bootstrap script: Symfony\Component\Finder\Exception\DirectoryNotFoundException:
The "/var/www/html/public/typo3/sysext/*/" directory does not exist.
#0 /var/www/html/vendor/typo3/cms-core/Classes/Package/PackageManager.php(350): Symfony\Component\Finder\Finder->in('/var/www/html/p...')
#1 /var/www/html/vendor/typo3/cms-core/Classes/Package/PackageManager.php(255): TYPO3\CMS\Core\Package\PackageManager->scanPackagePathsForExtensions()
#2 /var/www/html/vendor/typo3/cms-core/Classes/Package/UnitTestPackageManager.php(31): TYPO3\CMS\Core\Package\PackageManager->scanAvailablePackages()
#3 /var/www/html/vendor/typo3/cms-core/Classes/Core/Bootstrap.php(255): TYPO3\CMS\Core\Package\UnitTestPackageManager->initialize()
#4 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(71): TYPO3\CMS\Core\Core\Bootstrap::createPackageManager('TYPO3\\CMS\\Core\\...', Object(TYPO3\CMS\Core\Package\Cache\PackageStatesPackageCache))
#5 /var/www/html/vendor/typo3/testing-framework/Resources/Core/Build/UnitTestsBootstrap.php(84): PHPUnit\Util\FileLoader::{closure}()
#6 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(65): include_once('/var/www/html/v...')
#7 /var/www/html/vendor/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load('/var/www/html/v...')
#8 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(562): PHPUnit\Util\FileLoader::checkAndLoad('config/../vendo...')
#9 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(344): PHPUnit\TextUI\Command->handleBootstrap('config/../vendo...')
#10 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments(Array)
#11 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#12 /var/www/html/vendor/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#13 /var/www/html/vendor/bin/phpunit(123): include('/var/www/html/v...')
#14 {main}
```

### How to reproduce the issue?

Unfortunately, I cannot share my project (as it's a private customer project). Still, basically, it's something along the lines of:
1. create a new DDEV-based site installation from https://github.com/TYPO3/TYPO3.CMS.BaseDistribution
2. switch to typo3/cms-composer-installers v4.0.0-RC1
3. create and require a small (site) package that holds the tests
4. require the testing framework
5. write a dummy "hello world" unit test
6. run it

### Specify some data of the environment

- TYPO3 testing framework version: 6.16.6
- TYPO3 version: 11.5.16
- TYPO3 installation type: Composer within DDEV
- PHP version: 8.1.8
- Web server used + version: Apache 2.4.54
- Operating system: Linux

**Comment by sbuerk** [comment]
Small DemoProject for verification:
https://github.com/sbuerk/demoproject-core11_tf6_installers4

Had a "quick" look. UnitTests are mainly "executed" in the project or extension->build project context. It seems that in the core it builds the wrong path to "sysext", based on the "package path" (framework path => public path + typo3/sysexts/* ).

I think, here are still some parts missing at all or not finished. But this should need deeper investigation and work through all related parts.

**Comment by oliverklee** [comment]
Thanks, I will give that a try!

**Comment by sbuerk** [comment]
Report would be fine - not sure if there are other implications with that. In my simple test case "it worked". But just a quick shot.

**Comment by DanielSiepmann** [comment]
I guess I've run into the same. I expect the issue to be the installer (v5 for me) which no longer creates a sysext folder which should be linked by the testbase https://github.com/TYPO3/testing-framework/blob/main/Classes/Core/Testbase.php#L184

Error output is slightly different:
```
There was 1 error:

1) DanielSiepmann\Tracking\Tests\Functional\Command\UpdateDataCommandTest::updatesAllEntriesWithMissingOperatingSystem
symlink(): No such file or directory

/home/daniels/Projects/typo3/extensions/tracking/vendor/typo3/testing-framework/Classes/Core/Testbase.php:201
/home/daniels/Projects/typo3/extensions/tracking/vendor/typo3/testing-framework/Classes/Core/Functional/FunctionalTestCase.php:323
```

**Comment by sbuerk** [comment]
@DanielSiepmann Is this "project-level" testing or "extension-level" testing ? Yes, should be the same issue as with composer installers 5.

You may try my plugin, which helps with composer installers v5 and TYPO3v12 (which hard requires it) - as I check there for composer installers 4 and 5, it may help as intermediate solution there as well. But to be honest, never checked "project-level" testing yet.

(And with the plugin, the unit test workaround from above is not needed either):

https://github.com/sbuerk/typo3-cmscomposerinstallers-testingframework-bridge
```
composer require --dev sbuerk/typo3-cmscomposerinstallers-testingframework-bridge
```

Would be nice to no if it helps there to as intermediate solution. TF needs more work and also changes in core, which can not be simply added. And we may eventually move more to "composer installations" for test instances than "legacy installs" like now.

**Comment by brotkrueml** [comment]
@sbuerk I just want to give some feedback: I am using your bridge in extensions for functional testing which works. But sadly not on project level (the same error with symlink). For now I switch back (only for functional tests) to v3 so that those tests can be run.

**Comment by codemonkey1988** [comment]
@sbuerk I'm using your bridge extension after running into the same issues, that were mentions in this issue. Your bridge works fine for my extension based testing. Using it for unit and functional tests with TYPO3 10 - 12.  Thank you for providing it.

**Comment by sbuerk** [comment]
@brotkrueml

I think I have finished the project-level based support for the bridge plugin. Sadly, I do not have a working setup for project level based testing - and not the time right now to build one fictively up. However, having a local project and checking the symlink it should work. Prior, I had a "switch" for project level, but was not finished what to do there.

One thing ... the type of the root package *must* be `project`. If root package type is `typo3-cms-extension` it expectes extension level testing.

At least, extension leven testing is not broken. But maybe you can recheck and verify if it now works with v11 and composer installers 4 ?

```shell
composer require --dev \
  sbuerk/typo3-cmscomposerinstallers-testingframework-bridge:^0.1.0
```

**Comment by brotkrueml** [comment]
@sbuerk Yes, it works, thank you for the new version :-)

As I see, the extensions are additionally available in typo3conf/ext & typo3/sysext.

**Comment by sbuerk** [comment]
> As I see, the extensions are additionally available in typo3conf/ext & typo3/sysext.

Sadly yes. The testing-framework need it that way for now,
otherwise it cannot properly symlink the extension and core
extension during creating the "legacy install" instances for
functional tests.

That is the reason why the plugin should only be added as
development dependency. Sadly, this has one "draw-back" ..
as the extension and sysextension are symlinke, you will not
detect if you have not properly avoided linking to these
folders.

**Comment by sbuerk** [comment]
I worked on TF to ensure testing without (my) bridge plugin. I have currently version
for testing, and I tested it against core and some extensions that I know.

If the composer bridge plugin is removed, eventually adjustments on testing have to be
done. The reason for that is the way the bridge worked vs how the TF changes are working.

The `bridge` was a dirty little helper to create some symlinks to restore the expected
folder structure on how TF has been working. (core extensions and extensions in proper
paths, for extension testing root extension also symlinked).

The TF implementation I'm working on does no longer expect these folder structure. Instead
it uses the available composer runtime information for packages, as TF is usual installed
with composer. So instead of symlinking core extensions and extension from old legacy paths,
it symlinks the "selected" core extensions and extensions based on the composer data and from
the installed folder. It's not important if they are in `<public>/typo3conf/ext/*` or in the
vendor folder, or for system extension `<public>/typo3/sysext/*`.

From the past and as far as I have seen, most setups have been to call functional tests from
the installed instance folder (extension testing) and there in the `typo3conf/ext/<root-extension>` - which is not symlinked or provided since `typo3/cms-composer-installers` v5.

Sadly I have no current project at hand with project-level testing. Therefore I have not tested the TF changes yet against project-level testing against TYPO3 core v11 AND v12.

My tests showed, that TF6 should not be getting this change, as this breaks if used for TYPO3 v10 testing (at least TYPO3 core 10.4). So I would target this change only for TF 7 and main,
with that testing with core or extensions beginning with TYPO3 v11 and up is possible, even in multi core testing - and with composer installers 3 or 5 (4.0.0-RC1 test outstanding).

As already mentionend, eventually adjustment on test setup is needed. I provided pull-requests (currently draf) for some extensions, which is used to test these TF changes. These
pull-request can be used to update these extensions if TF changes are working and can be merged. DUring testing the bridge plugin **must** be removed to avoid false-positve because
of the provided symlinks.

:information_source: **Note**: the TF changes are currenlty more a `work-in-progress` or POC, but it would be nice if other can try them out to collect experience with them and different constellations. Eventually needed changes cann be looked up in the corresponding pull requests.

========================================

typo3/testing-framework
-----------------------

[MAIN] https://github.com/TYPO3/testing-framework/pull/434  (green)
[7]    https://github.com/TYPO3/testing-framework/pull/435  (green)
[6]    https://github.com/TYPO3/testing-framework/pull/436  (green)


lolli/dbdoctor
--------------

tf 7.x for testing against TYPO3 core v11 and v12,
with typo3/cms-composer-installers 3 for core v11
and typo3/cms-composer-installers v5 for core v12.

https://github.com/lolli42/dbdoctor/pull/26

sbuerk/typo3-ensure-admin
-------------------------

tf 7.x for testing against TYPO3 core v11 and v12,
with typo3/cms-composer-installers 3 for core v11
and typo3/cms-composer-installers v5 for core v12.


[main] https://github.com/sbuerk/typo3-ensure-admin/pull/6


ext:styleguide
--------------

main -> TF main         
11   -> TF 6
10   -> TF 6

[main] https://github.com/TYPO3/styleguide/pull/373     (green)
[11  ] -
[10  ] -


Checks / Validation against core
--------------------------------

main -> TF main (main-fix)
11.5 -> TF 6 (6-fix)
10.4 -> TF 6 (6-fix)

[MAIN] 77624: [WIP][TASK] Test TF typo3/cms-composer-installers 5 changes | https://review.typo3.org/c/Packages/TYPO3.CMS/+/77624       (green) 
[11.5] 77627: [WIP][TASK] Test TF typo3/cms-composer-installers 5 changes | https://review.typo3.org/c/Packages/TYPO3.CMS/+/77627       (green)
[10.4] 77628: [WIP][TASK] Test TF typo3/cms-composer-installers 5 changes | https://review.typo3.org/c/Packages/TYPO3.CMS/+/77628       (red)

**Comment by sbuerk** [comment]
Streamlined and reworked the solution. Test PR's are updated.
