### ISSUE TITLE
Add documentation for data scenario definition using YAML

### ISSUE THREAD

**Issue by ohader** [TYPO3/testing-framework#86]
see https://review.typo3.org/#/c/57867/3/typo3/sysext/frontend/Tests/Functional/SiteHandling/Fixtures/scenario.yaml

**Comment by lolli42** [comment]
Hey.

Nothing happened here since 2018, and the yaml based fe setup magic is most likely a thing that only core tests use. And yes, it's correct it's underdocumented. I think, if streamlining this, and maybe simplifying some parts of it, we could afterwards add more documentation to it - after we actively worked with it for a while again.

Since the issue was open for so long without anyone picking up, since it is more or less core-only, and since nobody is currently working in this area, I hope it's ok to close here for now: We'll simply push patches with more docs when this gains traction again. I hope that's fine.
